#! /usr/bin/env ruby
# Switch to git branch by matching part of a name

begin
  require 'tty-prompt'
  require 'tty-logger'
rescue LoadError
  puts 'Install the following gems to use this tool'
  puts 'gem install tty-prompt tty-logger'
  exit 0
end

search_term = ARGV[0]

logger = TTY::Logger.new

def prep_branch_results(results)
  results.split("\n").map { |bn| bn.sub(/^\*/, '').strip }
end

branch_names = prep_branch_results(`git branch -l | grep -i #{search_term} | cut -f 1`)

def select_branch(branches, branch_location)
  logger = TTY::Logger.new
  prompt = TTY::Prompt.new
  selection = prompt.select("Choose #{branch_location} branch", branches + ['none'])
  if selection == 'none'
    logger.info 'Cancelling selection'
    exit 0
  end
  `git checkout #{selection}`
  logger.success "Switched to #{branch_location} branch: #{selection}"
end

if branch_names.length == 1
  `git checkout #{branch_names.first}`
elsif branch_names.length > 1
  logger.warn 'More than one branch name matched'

  select_branch(branch_names, 'local')
else
  logger.warn 'No local branches with that name were found'
  remote_branches = prep_branch_results(`git branch -r | grep #{search_term} | cut -f 1`)

  select_branch(remote_branches, 'remote')
end
